from ccramic.utils.db import (
    preview_dataframe_from_db_config_list,
    format_blend_config_document_for_insert,
    match_db_config_to_request_str,
    extract_alias_labels_from_db_document)
import pandas as pd
import datetime

def test_generate_config_preview_table():
    config_list = [{'_id': "ObjectId('658ef3180aa56bb30f0fcfde')",
                    'user': 'mattsdwatson', 'name': 'first_blend_config',
                    'channels': {'ArAr80': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Y89': {'color': '#00FF00', 'x_lower_bound': 0, 'x_upper_bound': 1, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'In113': {'color': '#FF0000', 'x_lower_bound': 2, 'x_upper_bound': 4, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'In115': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Xe131': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Xe134': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ba136': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'La138': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pr141': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd142': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd143': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd144': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd145': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd146': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm147': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd148': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm149': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd150': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Eu151': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm152': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Eu153': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm154': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd155': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd156': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd158': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Tb159': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd160': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy161': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy162': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy163': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy164': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ho165': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er166': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er167': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er168': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Tm169': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er170': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb171': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb172': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb173': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb174': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Lu175': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb176': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ir191': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ir193': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pt196': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pb206': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}}, 'config': {'blend': ['Nd146', 'In113', 'Y89'], 'filter': {'global_apply_filter': [], 'global_filter_type': 'gaussian', 'global_filter_val': 3, 'global_filter_sigma': 1}}, 'modified': datetime.datetime(2023, 12, 29, 16, 25, 59, 712000)},
                   {'_id': "ObjectId('658ef3223e14178a98d340c4')", 'user': 'mattsdwatson', 'name': 'second_blend_config', 'channels': {'ArAr80': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Y89': {'color': '#00FF00', 'x_lower_bound': 0, 'x_upper_bound': 1, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'In113': {'color': '#FF0000', 'x_lower_bound': 2, 'x_upper_bound': 4, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'In115': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Xe131': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Xe134': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ba136': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'La138': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pr141': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd142': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd143': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd144': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd145': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd146': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm147': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd148': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm149': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd150': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Eu151': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm152': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Eu153': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm154': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd155': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd156': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd158': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Tb159': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd160': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy161': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy162': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy163': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy164': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ho165': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er166': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er167': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er168': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Tm169': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er170': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb171': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb172': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb173': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb174': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Lu175': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb176': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ir191': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ir193': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pt196': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pb206': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}}, 'config': {'blend': ['Nd146', 'In113', 'Y89'], 'filter': {'global_apply_filter': [], 'global_filter_type': 'gaussian', 'global_filter_val': 3, 'global_filter_sigma': 1}}, 'modified': "datetime.datetime(2023, 12, 29, 16, 26, 10, 607000)"}]

    frame = pd.DataFrame(preview_dataframe_from_db_config_list(config_list))
    assert len(frame) == 2
    assert list(frame['Names']) == ['first_blend_config', 'second_blend_config']

def test_basic_iteration_config_list():
    config_list = [{"name": "config_1", "blend": "insert_blend_here"}, {"name": "config_2", "blend": "new_blend"}]
    config_return = match_db_config_to_request_str(config_list, "config_1")
    assert config_return == {'name': 'config_1', 'blend': 'insert_blend_here'}
    assert match_db_config_to_request_str(config_list, "fake_key") is None

def test_create_insert_document_blend_config():
    blend_dict = {"ArAr80": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                             "filter_val": None, "filter_sigma": None},
                  "Y89": {"color": "#00FF00", "x_lower_bound": 0, "x_upper_bound": 1, "filter_type": None,
                          "filter_val": None, "filter_sigma": None},
                  "In113": {"color": "#FF0000", "x_lower_bound": 2, "x_upper_bound": 4, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "In115": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Xe131": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Xe134": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Ba136": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "La138": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Pr141": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd142": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd143": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd144": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd145": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd146": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Sm147": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd148": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Sm149": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd150": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Eu151": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Sm152": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Eu153": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Sm154": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Gd155": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Gd156": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Gd158": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Tb159": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Gd160": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Dy161": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Dy162": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Dy163": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Dy164": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Ho165": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Er166": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Er167": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Er168": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Tm169": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Er170": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Yb171": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Yb172": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Yb173": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Yb174": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Lu175": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Yb176": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Ir191": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Ir193": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Pt196": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Pb206": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None}}

    aliases = {}
    for key in blend_dict.keys():
        aliases[key] = key
    channel_list = ["Nd146", "In113", "Y89"]
    global_apply_filter = []
    global_filter_type = "gaussian"
    global_filter_val = 3
    global_filter_sigma = 1
    document = format_blend_config_document_for_insert("fake_user", "first_config", blend_dict, channel_list,
                                                       global_apply_filter, global_filter_type, global_filter_val,
                                                       global_filter_sigma, None, None, aliases)
    assert document == {'channels': {'ArAr80': {'alias': 'ArAr80',
                         'color': '#FFFFFF',
                         'filter_sigma': None,
                         'filter_type': None,
                         'filter_val': None,
                         'x_lower_bound': None,
                         'x_upper_bound': None},
              'Ba136': {'alias': 'Ba136',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy161': {'alias': 'Dy161',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy162': {'alias': 'Dy162',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy163': {'alias': 'Dy163',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy164': {'alias': 'Dy164',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er166': {'alias': 'Er166',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er167': {'alias': 'Er167',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er168': {'alias': 'Er168',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er170': {'alias': 'Er170',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Eu151': {'alias': 'Eu151',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Eu153': {'alias': 'Eu153',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd155': {'alias': 'Gd155',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd156': {'alias': 'Gd156',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd158': {'alias': 'Gd158',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd160': {'alias': 'Gd160',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Ho165': {'alias': 'Ho165',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'In113': {'alias': 'In113',
                        'color': '#FF0000',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': 2,
                        'x_upper_bound': 4},
              'In115': {'alias': 'In115',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Ir191': {'alias': 'Ir191',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Ir193': {'alias': 'Ir193',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'La138': {'alias': 'La138',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Lu175': {'alias': 'Lu175',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd142': {'alias': 'Nd142',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd143': {'alias': 'Nd143',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd144': {'alias': 'Nd144',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd145': {'alias': 'Nd145',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd146': {'alias': 'Nd146',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd148': {'alias': 'Nd148',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd150': {'alias': 'Nd150',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Pb206': {'alias': 'Pb206',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Pr141': {'alias': 'Pr141',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Pt196': {'alias': 'Pt196',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm147': {'alias': 'Sm147',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm149': {'alias': 'Sm149',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm152': {'alias': 'Sm152',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm154': {'alias': 'Sm154',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Tb159': {'alias': 'Tb159',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Tm169': {'alias': 'Tm169',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Xe131': {'alias': 'Xe131',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Xe134': {'alias': 'Xe134',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Y89': {'alias': 'Y89',
                      'color': '#00FF00',
                      'filter_sigma': None,
                      'filter_type': None,
                      'filter_val': None,
                      'x_lower_bound': 0,
                      'x_upper_bound': 1},
              'Yb171': {'alias': 'Yb171',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb172': {'alias': 'Yb172',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb173': {'alias': 'Yb173',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb174': {'alias': 'Yb174',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb176': {'alias': 'Yb176',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None}},
 'cluster': None,
 'config': {'blend': ['Nd146', 'In113', 'Y89'],
            'filter': {'global_apply_filter': [],
                       'global_filter_sigma': 1,
                       'global_filter_type': 'gaussian',
                       'global_filter_val': 3}},
 'gating': None,
 'name': 'first_config',
 'user': 'fake_user'}
    clusters = {"roi_1": {"cell_type_1": "#FFFFFF", "cell_type_2": "#FFFFFF"}}
    document_2 = format_blend_config_document_for_insert("fake_user", "first_config", blend_dict, channel_list,
                                                       global_apply_filter, global_filter_type, global_filter_val,
                                                       global_filter_sigma, "roi_1", clusters, aliases)

    assert document_2 == {'channels': {'ArAr80': {'alias': 'ArAr80',
                         'color': '#FFFFFF',
                         'filter_sigma': None,
                         'filter_type': None,
                         'filter_val': None,
                         'x_lower_bound': None,
                         'x_upper_bound': None},
              'Ba136': {'alias': 'Ba136',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy161': {'alias': 'Dy161',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy162': {'alias': 'Dy162',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy163': {'alias': 'Dy163',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy164': {'alias': 'Dy164',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er166': {'alias': 'Er166',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er167': {'alias': 'Er167',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er168': {'alias': 'Er168',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er170': {'alias': 'Er170',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Eu151': {'alias': 'Eu151',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Eu153': {'alias': 'Eu153',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd155': {'alias': 'Gd155',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd156': {'alias': 'Gd156',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd158': {'alias': 'Gd158',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd160': {'alias': 'Gd160',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Ho165': {'alias': 'Ho165',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'In113': {'alias': 'In113',
                        'color': '#FF0000',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': 2,
                        'x_upper_bound': 4},
              'In115': {'alias': 'In115',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Ir191': {'alias': 'Ir191',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Ir193': {'alias': 'Ir193',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'La138': {'alias': 'La138',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Lu175': {'alias': 'Lu175',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd142': {'alias': 'Nd142',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd143': {'alias': 'Nd143',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd144': {'alias': 'Nd144',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd145': {'alias': 'Nd145',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd146': {'alias': 'Nd146',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd148': {'alias': 'Nd148',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd150': {'alias': 'Nd150',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Pb206': {'alias': 'Pb206',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Pr141': {'alias': 'Pr141',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Pt196': {'alias': 'Pt196',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm147': {'alias': 'Sm147',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm149': {'alias': 'Sm149',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm152': {'alias': 'Sm152',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm154': {'alias': 'Sm154',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Tb159': {'alias': 'Tb159',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Tm169': {'alias': 'Tm169',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Xe131': {'alias': 'Xe131',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Xe134': {'alias': 'Xe134',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Y89': {'alias': 'Y89',
                      'color': '#00FF00',
                      'filter_sigma': None,
                      'filter_type': None,
                      'filter_val': None,
                      'x_lower_bound': 0,
                      'x_upper_bound': 1},
              'Yb171': {'alias': 'Yb171',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb172': {'alias': 'Yb172',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb173': {'alias': 'Yb173',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb174': {'alias': 'Yb174',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb176': {'alias': 'Yb176',
                        'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None}},
 'cluster': {'cell_type_1': '#FFFFFF', 'cell_type_2': '#FFFFFF'},
 'config': {'blend': ['Nd146', 'In113', 'Y89'],
            'filter': {'global_apply_filter': [],
                       'global_filter_sigma': 1,
                       'global_filter_type': 'gaussian',
                       'global_filter_val': 3}},
 'gating': None,
 'name': 'first_config',
 'user': 'fake_user'}

def test_extract_alias_labels():
    metadata_frame = pd.DataFrame({"channel": ['channel_1', 'channel_2'],
                                   'ccramic Label': ['channel_1', 'channel_2']})
    config = {"user": "user",
     "name": "test_config",
     "channels": {"channel_1": {"alias": "ch1"},
                  "channel_2": {"alias": "ch2"}},

     "config": {}}
    label_list = extract_alias_labels_from_db_document(config, metadata_frame)
    assert label_list ==[{'ccramic Label': 'ch1', 'channel': 'channel_1'},
        {'ccramic Label': 'ch2', 'channel': 'channel_2'}]

    config = {"user": "user",
              "name": "test_config",
              "channels": {"channel_1": {"alias": "ch1"},
                           "channel_2": {"alias": "ch2"},
                           "channel_3": {}},

              "config": {}}
    metadata_frame = pd.DataFrame({"channel": ['channel_1', 'channel_2', 'channel_3'],
                                   'ccramic Label': ['channel_1', 'channel_2', 'channel_3']})
    label_list = extract_alias_labels_from_db_document(config, metadata_frame)
    assert label_list == [{'ccramic Label': 'ch1', 'channel': 'channel_1'},
    {'ccramic Label': 'ch2', 'channel': 'channel_2'},
    {'ccramic Label': 'channel_3', 'channel': 'channel_3'}]

    assert extract_alias_labels_from_db_document({"user": "fake_user"}) is None
