from ccramic.utils.db import (
    preview_dataframe_from_db_config_list,
    format_blend_config_document_for_insert)
import pandas as pd
import datetime

def test_generate_config_preview_table():
    config_list = [{'_id': "ObjectId('658ef3180aa56bb30f0fcfde')",
                    'user': 'mattsdwatson', 'name': 'first_blend_config',
                    'channels': {'ArAr80': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Y89': {'color': '#00FF00', 'x_lower_bound': 0, 'x_upper_bound': 1, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'In113': {'color': '#FF0000', 'x_lower_bound': 2, 'x_upper_bound': 4, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'In115': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Xe131': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Xe134': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ba136': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'La138': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pr141': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd142': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd143': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd144': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd145': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd146': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm147': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd148': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm149': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd150': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Eu151': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm152': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Eu153': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm154': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd155': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd156': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd158': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Tb159': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd160': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy161': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy162': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy163': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy164': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ho165': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er166': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er167': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er168': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Tm169': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er170': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb171': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb172': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb173': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb174': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Lu175': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb176': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ir191': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ir193': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pt196': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pb206': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}}, 'config': {'blend': ['Nd146', 'In113', 'Y89'], 'filter': {'global_apply_filter': [], 'global_filter_type': 'gaussian', 'global_filter_val': 3, 'global_filter_sigma': 1}}, 'modified': datetime.datetime(2023, 12, 29, 16, 25, 59, 712000)},
                   {'_id': "ObjectId('658ef3223e14178a98d340c4')", 'user': 'mattsdwatson', 'name': 'second_blend_config', 'channels': {'ArAr80': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Y89': {'color': '#00FF00', 'x_lower_bound': 0, 'x_upper_bound': 1, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'In113': {'color': '#FF0000', 'x_lower_bound': 2, 'x_upper_bound': 4, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'In115': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Xe131': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Xe134': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ba136': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'La138': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pr141': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd142': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd143': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd144': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd145': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd146': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm147': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd148': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm149': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Nd150': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Eu151': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm152': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Eu153': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Sm154': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd155': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd156': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd158': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Tb159': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Gd160': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy161': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy162': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy163': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Dy164': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ho165': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er166': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er167': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er168': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Tm169': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Er170': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb171': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb172': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb173': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb174': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Lu175': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Yb176': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ir191': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Ir193': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pt196': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}, 'Pb206': {'color': '#FFFFFF', 'x_lower_bound': None, 'x_upper_bound': None, 'filter_type': None, 'filter_val': None, 'filter_sigma': None}}, 'config': {'blend': ['Nd146', 'In113', 'Y89'], 'filter': {'global_apply_filter': [], 'global_filter_type': 'gaussian', 'global_filter_val': 3, 'global_filter_sigma': 1}}, 'modified': "datetime.datetime(2023, 12, 29, 16, 26, 10, 607000)"}]

    frame = pd.DataFrame(preview_dataframe_from_db_config_list(config_list))
    assert len(frame) == 2
    assert list(frame['Names']) == ['first_blend_config', 'second_blend_config']

def test_create_insert_document_blend_config():
    blend_dict = {"ArAr80": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                             "filter_val": None, "filter_sigma": None},
                  "Y89": {"color": "#00FF00", "x_lower_bound": 0, "x_upper_bound": 1, "filter_type": None,
                          "filter_val": None, "filter_sigma": None},
                  "In113": {"color": "#FF0000", "x_lower_bound": 2, "x_upper_bound": 4, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "In115": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Xe131": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Xe134": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Ba136": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "La138": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Pr141": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd142": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd143": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd144": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd145": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd146": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Sm147": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd148": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Sm149": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Nd150": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Eu151": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Sm152": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Eu153": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Sm154": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Gd155": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Gd156": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Gd158": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Tb159": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Gd160": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Dy161": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Dy162": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Dy163": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Dy164": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Ho165": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Er166": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Er167": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Er168": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Tm169": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Er170": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Yb171": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Yb172": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Yb173": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Yb174": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Lu175": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Yb176": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Ir191": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Ir193": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Pt196": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None},
                  "Pb206": {"color": "#FFFFFF", "x_lower_bound": None, "x_upper_bound": None, "filter_type": None,
                            "filter_val": None, "filter_sigma": None}}

    channel_list = ["Nd146", "In113", "Y89"]
    global_apply_filter = []
    global_filter_type = "gaussian"
    global_filter_val = 3
    global_filter_sigma = 1
    document = format_blend_config_document_for_insert("fake_user", "first_config", blend_dict, channel_list,
                                                       global_apply_filter, global_filter_type, global_filter_val,
                                                       global_filter_sigma)
    assert document == {'channels': {'ArAr80': {'color': '#FFFFFF',
                         'filter_sigma': None,
                         'filter_type': None,
                         'filter_val': None,
                         'x_lower_bound': None,
                         'x_upper_bound': None},
              'Ba136': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy161': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy162': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy163': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Dy164': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er166': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er167': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er168': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Er170': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Eu151': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Eu153': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd155': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd156': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd158': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Gd160': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Ho165': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'In113': {'color': '#FF0000',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': 2,
                        'x_upper_bound': 4},
              'In115': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Ir191': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Ir193': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'La138': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Lu175': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd142': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd143': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd144': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd145': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd146': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd148': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Nd150': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Pb206': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Pr141': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Pt196': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm147': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm149': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm152': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Sm154': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Tb159': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Tm169': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Xe131': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Xe134': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Y89': {'color': '#00FF00',
                      'filter_sigma': None,
                      'filter_type': None,
                      'filter_val': None,
                      'x_lower_bound': 0,
                      'x_upper_bound': 1},
              'Yb171': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb172': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb173': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb174': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None},
              'Yb176': {'color': '#FFFFFF',
                        'filter_sigma': None,
                        'filter_type': None,
                        'filter_val': None,
                        'x_lower_bound': None,
                        'x_upper_bound': None}},
 'config': {'blend': ['Nd146', 'In113', 'Y89'],
            'filter': {'global_apply_filter': [],
                       'global_filter_sigma': 1,
                       'global_filter_type': 'gaussian',
                       'global_filter_val': 3}},
 'name': 'first_config',
 'user': 'fake_user'}
