from dash import dash_table
import dash_uploader as du
from dash_extensions import EventListener
import dash_daq as daq
from ccramic.inputs.pixel_level_inputs import (
    render_default_annotation_canvas,
    add_local_file_dialog)
from ccramic.inputs.loaders import wrap_child_in_loading
from ccramic.utils.pixel_level_utils import generate_default_swatches
import dash_ag_grid as dag
import dash_mantine_components as dmc
from plotly.graph_objs.layout import YAxis, XAxis
from ccramic.entrypoint import __version__
from dash import dcc, html
import dash_bootstrap_components as dbc
import dash_tour_component
from ccramic.utils.alert import DataImportTour
from ccramic.io.session import SessionTheme, TabText


def register_app_layout(config, cache_dest):

    # set the default colours for the swatches from the config input
    DEFAULT_SWATCHES = generate_default_swatches(config)
    DEFAULT_WIDGET_COLOUR = SessionTheme().widget_colour

    return html.Div([
        dash_tour_component.DashTour(accentColor=DEFAULT_WIDGET_COLOUR,
            steps= DataImportTour().steps, isOpen=False, id="tour_component"),
        # this is the generic error modal that will pop up on specific errors return by the alert dict
        dbc.Modal(children=dbc.ModalBody([html.Div(id='alert-information', style={'whiteSpace': 'pre-line'})]),
                  id="alert-modal", size='xl'),
        # this modal is for the fullscreen view and does not belong in a nested tab
        dbc.Modal(children=[dbc.ModalHeader(),
            dbc.ModalBody([render_default_annotation_canvas(input_id="annotation_canvas-fullscreen",
                                                                           fullscreen_mode=True)])],
            id="fullscreen-canvas", fullscreen=True, size='xl',
        centered=True, style={"margin": "auto", "width": "100vw", "height": "100vh",
                              "max-width": "none", "max-height": "none"}),
        # modal for the dataset information
        dbc.Modal(children=dbc.ModalBody([dash_table.DataTable(id='dataset-preview-table', columns=[], data=None,
                                            editable=False, filter_action='native', row_selectable='single',
                                                               column_selectable='single')]),
                  id="dataset-preview", size='xl'),
        html.Header(
            className="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow",
            children=[
                html.A("ccramic", className="navbar-brand me-0 px-3", href="#"),
                html.Div([
                    html.A("Documentation", id='ccramic-documentation',
                             href='https://camlab-bioml.github.io/ccramic-doc/', target="_blank",
                           style={"display": "flex", "margin-top": "7.5px", "color": "#FFFFFF",
                                  "text-decoration": "None", "margin-right": "10px"}),
                    dbc.Button(
                    children=html.Span([html.I(className="fa-solid fa-gears",
                                               style={"display": "inline-block"}),
                                        ]),
                    id="session-config-modal-button", className="navbar-brand me-0 px-3",
                    color=None, n_clicks=0, style={"display": "flex"}, outline=True),
                dbc.Modal(children=dbc.ModalBody([
                    html.H5("Set additional session variables"),
                    html.Br(),
                    html.Div([html.B("Select dataset identifier delimiter", style={"margin-right": "20px"}),
                             dcc.Input(id="dataset-delimiter", value="+++", type="text", debounce=True,
                              persistence=config['persistence'], persistence_type='local', style={"width": "20%"}),
                    dbc.Tooltip("Set a custom delimiter for the string representation of datasets. "
                                "Should be used if imported datasets contain filenames or identifiers with"
                                "string overlap with the current delimiter.",
                                target="dataset-delimiter")], style={"display": "flex"}),
                    html.Br(),
                    html.Div([daq.ToggleSwitch(label='Enable canvas scroll zoom', id='enable-canvas-scroll-zoom',
                                     labelPosition='bottom', color=DEFAULT_WIDGET_COLOUR, value=False,
                                     persistence=config['persistence'], persistence_type='local'),
                    daq.ToggleSwitch(label='ROI change using arrow keys', id='enable-roi-change-key',
                        labelPosition='bottom', color=DEFAULT_WIDGET_COLOUR, value=True,
                        persistence=config['persistence'], persistence_type='local',
                                     style={"margin-left": "10px"})], style={"display": "flex",
                                    "justify-content": "center"}),
                    html.Br(),
                    html.Div([html.B("Set annotation circle radius", style={"margin-right": "20px"}),
                    dcc.Input(id='annotation-circle-size', type='number', value=4, style={"width": "25%",
                            "margin-top": "-3px"}, persistence=config['persistence'], persistence_type='local')],
                    style={"display": "flex"}),
                    html.Br(),
                    html.Div([daq.ToggleSwitch(label='Autofill channel colours', id='autofill-channel-colors',
                                     labelPosition='bottom', color=DEFAULT_WIDGET_COLOUR, value=False,
                                     persistence=config['persistence'], persistence_type='local',
                                               style={"margin-right": "10px"}),
                    html.Br(),
                    daq.ToggleSwitch(label='Natural sort input files', id='natsort-uploads',
                                     labelPosition='bottom', color=DEFAULT_WIDGET_COLOUR, value=True,
                                     persistence=config['persistence'], persistence_type='local',
                            style={"margin-left": "10px"})],
                             style={"display": "flex", "justify-content": "center"}),
                    # daq.ToggleSwitch(label='Cache blends between ROIS', id='roi-blend-cache',
                    #                  labelPosition='bottom', color="blue", value=False,
                    #                  persistence=config['persistence'], persistence_type='local'),
                    html.Br(),
                    html.Div([html.B("Legend orientation"),
                    dcc.RadioItems(['vertical', 'horizontal'], 'vertical', inline=True, id="legend_orientation",
                                   persistence=config['persistence'], persistence_type='local',
                                   style={"accent-color": DEFAULT_WIDGET_COLOUR}),
                    html.Br(),
                    html.B("Scalebar color"),
                    dcc.RadioItems(['white', 'black'], 'white', inline=True, id="scalebar-color",
                                   persistence=config['persistence'], persistence_type='local',
                                   style={"accent-color": DEFAULT_WIDGET_COLOUR})], style={"display": "flex"}),
                    html.Br(),
                    html.Br(),
                    html.H6(f"Session cache: {cache_dest}"),
                    # html.A(dbc.Button('Refresh app and clear previous data caches', id='refresh-app'),
                    #        id='app_dest', href='/ccramic/'),
                ]),
                        id="session-config-modal", size='l',
                        style={"margin-left": "10px", "margin-top": "15px"}),
                html.A(f"v{__version__}", className="navbar-brand me-0 px-3", href="#")], style={"display": "flex"})],
            style={"margin-bottom": "15px"}),
            html.H6(id="current-roi-ha", style={"float": "right"}),
            dbc.Tab(label='Image annotation', tab_id='image-annotation',
                    active_label_style={"color": DEFAULT_WIDGET_COLOUR},
                    children=[
                html.Div([dbc.Tabs(id='pixel-level-analysis',
                children=[dbc.Tab(# label_class_name="fa-regular fa-file-image",
                                  label="Image analysis",
                                    label_style={"color": DEFAULT_WIDGET_COLOUR},
                                  # label_style={"text-transform": "capitalize", "font-weight": "normal"},
                tab_id='pixel-analysis',
                children=[
                    dbc.Offcanvas(
                        id="inputs-offcanvas",
                        title="Configure inputs for ccramic",
                        is_open=True,
                        children=[dbc.Tabs(id='data-config',
                                children=[dbc.Tab(id='file-data-config', label='File import',
                                                  label_style={"color": DEFAULT_WIDGET_COLOUR},
                                children=[
                                html.Br(),
                                html.Div([html.H5("Import images", style={'width': '35%'}),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-circle-question",
                                style={"display": "inline-block", "margin-right": "7.5px",
                                "margin-top": "-5px"})],
                                style={"display": "flex"}), id="dash-import-tour",
                                className="mb-3", color=None, n_clicks=0, style={"width": "20%",
                                    "margin-top": "-3px"})], style={"display": "flex"}),
                                dbc.Tooltip("Click here to get a tour of the components required for dataset import.",
                                    target="dash-import-tour"),
                                du.Upload(id='upload-image', max_file_size=30000,
                                              text='Import imaging data from MCD or tiff files using drag and drop',
                                              chunk_size=100,
                                              max_total_size=30000, max_files=200,
                                              filetypes=['png', 'tif', 'tiff', 'h5', 'mcd', 'txt'],
                                              default_style={"margin-top": "20px",
                                                             "height": "10vh"}),
                                    html.Br(),
                                    dcc.Input(id="read-filepath", type="text",
                                              placeholder="Import file(s) using filepath or directory (local runs only)",
                                              value=None, style={"width": "100%", "height": "10%"}),
                                    html.Br(),
                                    html.Div([dcc.RadioItems(['filepath', 'directory'], 'filepath',
                                                             id="local-read-type",
                                                             style={"margin-top": "10px", "margin-left": "15px",
                                                        "margin-right": "15px", "accent-color": DEFAULT_WIDGET_COLOUR}),
                                              dbc.Button("Import local", id="add-file-by-path",
                                                         className="mb-3", color="primary", n_clicks=0,
                                                         style={"margin-top": "10px",
                                                                "margin-left": "15px",
                                                                "background-color": DEFAULT_WIDGET_COLOUR})],
                                             style={"display": "flex"}),
                                    add_local_file_dialog(use_local_dialog=config['use_local_dialog']),
                                    dbc.Tooltip("Browse the local file system using a dialog."
                                                " IMPORTANT: may not be compatible with the specific OS.",
                                                target="local-dialog-file"),
                                    html.Div([html.Span([
                                        dbc.Button(children=html.Span([html.I(className="fa-solid fa-circle-info",
                                                                              style={"display": "inline-block",
                                                                                     "margin-right": "7.5px",
                                                                                     "margin-top": "3px"}),
                                                                       html.Div("Dataset info")],
                                                                      style={"display": "flex"}),
                                                   id="show-dataset-info",
                                                   className="mb-3", color="primary", n_clicks=0,
                                                   style={"margin-top": "10px", "background-color": DEFAULT_WIDGET_COLOUR}),
                                        dbc.Button(children=html.Span([html.Abbr(html.I(className="fa fa-trash",
                                                                                        style={"display": "iflex"}))],
                                                                      style={"width": "100vw"}),
                                                   id="remove-collection", color=None, n_clicks=0,
                                                   style={"margin-top": "-5px", "height": "10%"}),
                                        dbc.Tooltip("Remove the current data collection. "
                                                    "(IMPORTANT): cannot be undone.", target="remove-collection")],
                                        style={"width": "100%"}),
                                        html.Br(),
                                        html.Br(),
                                        html.H5("Choose data collection/ROI", style={'width': '65%'}),
                                        # TODO: set dropdown height based on length
                                        # https://community.plotly.com/t/long-dropdown-values-overlap/14843
                                        dcc.Dropdown(id='data-collection', multi=False, options=[],
                                                     style={'width': '100%'}),
                                        html.Br(),
                                        dbc.Button("Refresh selection", id="data-selection-refresh", className="me-1",
                                        size="sm", color='dark', outline=True, style={"float": "left",
                                                "margin-right": "12.5px", "height": "50%"}),
                                        dbc.Tooltip("Refresh the current dataset selection. "
                                        "Can be used if the ROI loading has become corrupted", target="data-selection-refresh"),
                                        html.Br(),
                                        html.Br(),
                                        html.H5("Import mask"),
                                        dbc.Modal(children=dbc.ModalBody(
                                            [html.H6("Set the label for the imported mask"),
                                             html.Div([dcc.Input(id="input-mask-name", type="text", value=None,
                                                                 style={"width": "65%", "margin-right": "10px",
                                                                        "height": "50%"}),
                                                       ],
                                                      style={"display": "flex"}),
                                        html.Br(),
                                             dbc.Button("Set mask import", id="set-mask-name", className="me-1",
                                                        style={"background-color": DEFAULT_WIDGET_COLOUR})]),
                                            id="mask-name-modal", size='l',
                                            style={"margin-left": "10px", "margin-top": "15px"}),
                                        du.Upload(id='upload-mask', max_file_size=30000,
                                                  text='Import mask in tiff format using drag and drop',
                                                  max_total_size=30000, max_files=500,
                                                  chunk_size=100,
                                                  filetypes=['tif', 'tiff'],
                                                  default_style={"margin-top": "20px", "height": "10%"}),
                                        html.Br(),
                                        html.H5("Import quantification results"),
                                        du.Upload(id='upload-quantification', max_file_size=5000,
                                                  filetypes=['h5ad', 'h5', 'csv'],
                                                  text='Import cell quantification results in CSV format using drag and drop',
                                                  max_files=1, upload_id="upload-quantification",
                                                  default_style={"margin-top": "20px", "height": "10%"}),
                                        html.Br(),
                                        html.H5("Import ROI configuration"),
                                        du.Upload(id='upload-param-json', max_file_size=1000,
                                                  filetypes=['json'],
                                                  text='Import channel blend parameters in JSON format using drag and drop',
                                                  max_files=1, upload_id="upload-param-json",
                                                  default_style={"margin-top": "20px", "height": "10%"}),
                                        html.Br(),
                                        html.H5("Downloads"),
                                        dcc.Checklist(options=[' use graph subset on download'], value=[],
                                                      id="graph-subset-download", style={"margin-top": "12px",
                                                    "accent-color": DEFAULT_WIDGET_COLOUR}),
                                        dcc.Download(id="download-canvas-image-tiff"),
                                        dbc.Button(children=html.Span([html.I(className="fa-solid fa-download",
                                                                              style={"display": "inline-block",
                                                                                     "margin-right": "7.5px",
                                                                                     "margin-top": "3px"}),
                                                                       html.Div("Download image (tiff)")],
                                                                      style={"display": "flex"}),
                                                   id="btn-download-canvas-tiff", className="mx-auto", color=None,
                                                   n_clicks=0, style={"margin-top": "10px"}),
                                        # TODO: add back in component for tiff w/ annotations when fixed
                                        # dcc.Download(id="download-canvas-image-tiff-annotations"),
                                        # dbc.Button(children=html.Span([html.I(className="fa-solid fa-download",
                                        # style={"display": "inline-block", "margin-right": "7.5px",
                                        # "margin-top": "3px"}),
                                        # html.Div("Download image w/ annotations (tiff)")], style={"display": "flex"}),
                                        # id="btn-download-canvas-tiff-annotations", className="mx-auto", color=None,
                                        # n_clicks=0, style={"margin-top": "10px"}),
                                        dcc.Download(id="download-canvas-image-html"),
                                        dbc.Button(children=html.Span([html.I(className="fa-solid fa-download",
                                                                              style={"display": "inline-block",
                                                                                     "margin-right": "7.5px",
                                                                                     "margin-top": "3px"}),
                                                                       html.Div("Download canvas (HTML)")],
                                                                      style={"display": "flex"}),
                                                   id="btn-download-canvas-html", className="mx-auto", color=None,
                                                   n_clicks=0, style={"margin-top": "10px"}),
                                        dcc.Download(id="download-session-config-json"),
                                        dbc.Button(children=html.Span([html.I(className="fa-solid fa-download",
                                                                              style={"display": "inline-block",
                                                                                     "margin-right": "7.5px",
                                                                                     "margin-top": "3px"}),
                                                                       html.Div("Download session as JSON")],
                                                                      style={"display": "flex"}),
                                                   id="btn-download-session-config-json", className="mx-auto",
                                                   color=None,
                                                   n_clicks=0, style={"margin-top": "10px"}),
                                        dcc.Download(id="download-roi-h5py"),
                                        dbc.Button(children=html.Span([html.I(className="fa-solid fa-download",
                                                                              style={"display": "inline-block",
                                                                                     "margin-right": "7.5px",
                                                                                     "margin-top": "3px"}),
                                                                       html.Div("Download ROI as h5py")],
                                                                      style={"display": "flex"}),
                                                   id="btn-download-roi-h5py", className="mx-auto", color=None,
                                                   n_clicks=0, style={"margin-top": "10px"}),
                                    ],
                                        style={'width': '100%', 'height': '100%', "margin-top": "5px"})

                                ]),
                                dbc.Tab(id='db-config', label='mongoDB',
                                        label_style={"color": DEFAULT_WIDGET_COLOUR},
                                children=[
                                html.Br(),
                                dbc.Form([
                                html.Div([dbc.Label("Username", html_for="db-username"),
                                dbc.Input(type="text", id="db-username", placeholder="Enter username",
                                style={"width": "75%"}, persistence=config['persistence'],
                                persistence_type='local')], className="mb-3"),
                                html.Div([
                                dbc.Label("Password", html_for="db-password"),
                                dbc.Input(type="password", id="db-password", placeholder="Enter password",
                                          style={"width": "75%"}, persistence=config['persistence'],
                                          persistence_type='local'),
                                dbc.FormText("Enter your credentials for the mongoDB instance", color="secondary"),
                                ], className="mb-3")
                                ]),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-arrow-right-to-bracket",
                                    style={"display": "inline-block", "margin-right": "7.5px",
                                        "margin-top": "3px"}), html.Div("Connect")],
                                    style={"display": "flex"}), id="db-connect",
                                               className="mb-3", color="secondary", n_clicks=0,
                                               style={"margin-top": "10px"}),
                                dcc.Loading(dbc.Alert([], color='danger', is_open=False, id='db-connect-alert'),
                                            fullscreen=False, color=DEFAULT_WIDGET_COLOUR),
                                html.Br(),
                                html.H6("Select saved configuration"),
                                dcc.Dropdown(id='db-config-options', multi=False, style={"width": "87%"}),
                                html.Br(),
                                html.Br(),
                                html.Br(),
                                dbc.Button("View imported configurations", id="view-db-config-list",
                                style={"width": "60%", "background-color": DEFAULT_WIDGET_COLOUR}),
                                dbc.Modal(children=dbc.ModalBody(
                                [dash_table.DataTable(id='db-config-preview-table', columns=[], data=None,
                                                              editable=False, filter_action='native',
                                                              row_selectable='single',
                                                              column_selectable='single',
                                                      )]),
                                id='db-config-preview', size='xl'),
                                html.Br(),
                                html.Br(),
                                dcc.Loading(dbc.Alert([], color='success', is_open=False, duration=1500,
                                        id='db-config-submit-alert'), fullscreen=False, color=DEFAULT_WIDGET_COLOUR),
                                html.Div([
                                dbc.Input(type="text", id="db-config-name", placeholder="Enter configuration name",
                                                  style={"width": "75%"}),
                                dbc.FormText("Set the name of the current configuration to save to the database",
                                color="secondary"),
                                    ], className="mb-3"),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-database",
                                style={"display": "inline-block", "margin-right": "7.5px",
                                "margin-top": "3px"}), html.Div("Save current session")],
                                    style={"display": "flex"}), id="db-save-cur-config",
                                        className="mb-3", color="dark", n_clicks=0, outline=True,
                                        style={"margin-top": "10px"}),
                                html.Br(),
                                html.Br(),
                                html.Br(),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-trash",
                                    style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                                    html.Div("Remove selected config")],
                                    style={"display": "flex"}), id="db-remove-select-config",
                                        className="mb-3", color=None, n_clicks=0, outline=False,
                                        style={"margin-top": "10px"}, size='s'),
                                ])],
                                style={"margin-top": "-15px"})],
                    style={"width": "35%", "padding": "5px", "margin-bottom": "0px"}, scrollable=True),
                        # style={'width': '100%', 'height': '100%', "margin-top": "5px"}
                        #          )], style={"width": "33%", "padding": "5px", "margin-bottom": "0px"},
                    # scrollable=True),
                    html.Div([dbc.Row([dbc.Col(html.Div([
                        dbc.Row([dbc.Col(html.Div([dbc.Button(
                        children=html.Span([html.I(className="fa-solid fa-solid fa-solid fa-file-export",
                        style={"display": "inline-block"}),html.Div("Show import panel")],
                        style={"margin-top": "-5px", "margin-bottom": "10px"}),
                                   id="inputs-offcanvas-button",
                                   color=None, n_clicks=0,
                                   style={"margin-top": "10px"}),]), width=2),
                                 dbc.Col([html.Div([html.H5("Channel selection", style={"margin-top": "13.5px",
                                                                                        "float": "left"}),
                                          dcc.Checklist(options=[' sort (A-z)'], value=[],
                                        id="sort-channels-alpha", style={"width": "20%", "float": "right",
                                        "justifyContent": "right", "margin-left": "200px", "margin-top": "12px",
                                            "accent-color": DEFAULT_WIDGET_COLOUR},
                                        persistence=config['persistence'], persistence_type='local')],
                                                   style={"display": "flex"}),
                                          dcc.Dropdown(id='image_layers', multi=True, value=[],
                                     style={"margin-top": "10px"})],
                                         width=6, style={"display": "inline-block"}),
                        dbc.Col([html.H6("Canvas size"),
                                           dcc.Slider(50, 150, 5, value=100,
                                                      id='annotation-canvas-size',
                                   marks={50: 'small', 100: 'default',
                                          150: 'large'})],width=4, style={"display": "inline-block",
                                        "margin-top": "15px"})]),
                        dbc.Row([dbc.Col(width=2),
                        dbc.Col([html.Div([], style={"margin-top": "15px", "width": "100%",
                                                        "float": "left", "display": "inline-block"})], width=6)],
                                style={"display": "flex"}),
                        dbc.Row([dbc.Col([html.Div([dbc.Button(
                            children=html.Span([html.Div("Fullscreen"),
                                html.I(className="fa-solid fa-display", style={"display": "inline-block"}),
                                  ], style={"width": "100vw", "margin-top": "-5px", "margin-bottom": "10px"}),
                                             id="make-canvas-fullscreen",
                                            color=None, n_clicks=0,
                                style={"margin-left": "10px", "margin-top": "0px", "height": "100%"}),
                                # dbc.Button(children=html.Span([html.Div("Auto-fit"),
                                # html.I(className="fa-solid fa-arrows-left-right-to-line", style={"display": "inline-block"}),
                                #   ], style={"width": "100vw", "margin-top": "-5px", "margin-bottom": "10px"}),
                                #            id="autosize-canvas", color=None, n_clicks=0, style={"margin-left": "10px",
                                #     "height": "100%", "width": "auto"}),
                            dbc.Button(children=html.Span([html.Div("Prev ROI"),
                                                           html.I(className="fa-solid fa-arrow-left",
                                                                  style={"display": "inline-block"}),
                                                           ], style={"width": "100vw", "margin-top": "-5px",
                                                                     "margin-bottom": "10px"}),
                                       id="prev-roi", color=None, n_clicks=0, style={"margin-left": "5px",
                                                                                     "height": "100%", "width": "auto"}),
                            dbc.Button(children=html.Span([html.Div("Next ROI"),
                            html.I(className="fa-solid fa-arrow-right", style={"display": "inline-block"}),
                              ], style={"width": "100vw", "margin-top": "-5px", "margin-bottom": "5px"}),
                                       id="next-roi", color=None, n_clicks=0, style={"margin-left": "5px",
                                "height": "100%", "width": "auto"})])],
                                         width=4, style={"display": "inline-block"}),
                                 dbc.Col(html.Div(style={"margin-top": "20px", "height": "100%",
                                                  "width": "auto"},
                                          id="bound-shower"), width=4, style={"float": "left", "display": "flex",
                                                                              }),
                                 dbc.Col([dcc.Input(id="set-x-auto-bound", type="number", value=None,
                                            placeholder="Set x-coord",
                                            style={"margin-left": "10px",
                                                   "margin-top": "15px", "width": "30%"}
                                            ),
                                  dcc.Input(id="set-y-auto-bound", type="number", value=None,
                                            placeholder="Set y-coord",
                                            style={"margin-left": "10px",
                                                   "margin-top": "20px", "width": "30%", "margin-right": "-10px"}
                                            ),
                                  dbc.Button(html.Span([html.Div("Set", style={"margin-right": "5px", "height": "150%",
                                                                               "font-size": "16px"}),
                                                        html.I(className="fa-solid fa-location-dot",
                                                                  style={"display": "inline-block",
                                                                         "margin-right": "7.5px", "margin-top": "3px"}),
                                                           ],
                                                          style={"display": "flex"}), id="activate-coord",
                                             color=None, n_clicks=0,
                                             style={"margin-left": "-75px",
                                                    "float": "right", "margin-top": "15px", "margin-right": "15px"})],
                                         width=4, style={"float": "right", "margin": "0px", "margin-top": "-5px"})
                                 ], style={"display": "flex", "margin": "0px"}),
                        html.Div([render_default_annotation_canvas(input_id="annotation_canvas")],
                                 style={"display": "flex", "justifyContent": "center"},
                                 id="canvas-div-holder"),
                    # html.Div(id='blend-color-legend', style={'whiteSpace': 'pre-line'}),
                    ]),width=9),
                        dbc.Col([
                            html.Div(
                                [html.H5("Channel modification",
                                         style={'width': '75%', 'display': 'inline-block', "margin-top": "3px",
                                                "margin-left": "10px"}),
                                 html.Abbr("\u2753", title="Select a channel in the current blend to \nchange colour, "
                                                           "pixel intensity, or apply a filter.",
                                           style={'width': '5%', 'display': 'inline-block'}),
                                 dcc.Dropdown(id='images_in_blend', multi=False),
                                 html.Br(),
                                 daq.ColorPicker(id="annotation-color-picker", label="Current channel color",
                                                 value=dict(hex="#00ABFC", rgb=None)),
                                 dmc.Center([dmc.ColorPicker(swatches=DEFAULT_SWATCHES,
                                swatchesPerRow=7, size = 'xs', withPicker=False, id="swatch-color-picker",
                                fullWidth=False, persistence=config['persistence'], persistence_type='local',
                                    persisted_props='swatches')]),
                                 dbc.Button(children=html.Span([html.I(className="fa-solid fa-signal",
                                style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                                html.Div("Show/hide pixel histogram")],
                                style={"display": "flex", "margin-top": "10px"}), id="show-pixel-hist",
                                className="mx-auto", color="light", n_clicks=0,
                                style={"display": "flex", "width": "auto", "align-items": "center",
                                "float": "center", "justify-content": "center"}),
                                html.Div(dbc.Collapse(html.Div([html.H6("Pixel histogram", style={'width': '75%'}),
                                html.Div([dcc.Loading(dcc.Graph(id="pixel-hist", figure={'layout': dict(
                                xaxis_showgrid=False, yaxis_showgrid=False, xaxis=XAxis(showticklabels=False),
                                yaxis=YAxis(showticklabels=False), margin=dict(l=5, r=5, b=15, t=20, pad=0))},
                                style={'width': '60vh', 'height': '30vh', 'margin-left': '-30px'},
                                # config={"modeBarButtonsToAdd": ["drawrect", "eraseshape"],
                                # keep zoom and pan bars to be able to modify the histogram view
                                # 'modeBarButtonsToRemove': ['zoom', 'pan']
                                # },
                                config={'displaylogo': False},
                                ), type="default", fullscreen=False, color=DEFAULT_WIDGET_COLOUR)])]),
                                id="pixel-hist-collapse", is_open=False), style={"minHeight": "100px"}),
                                 html.Div([
                                dcc.RangeSlider(0, 100, 1, value=[None, None],
                                marks=dict([(i, str(i)) for i in range(0, 100, 25)]),
                                id='pixel-intensity-slider', allowCross=False,
                                tooltip={"placement": "top", "always_visible": False})],
                                          style={"width": "96.5%", "margin-left": "27px", "margin-top": "-50px"}),
                                html.Div([dbc.Button("Reset to default", id="set-default-rangeslider", className="me-1",
                                size="sm", color='dark', outline=True, style={"float": "left",
                                        "margin-right": "12.5px", "height": "50%"}),
                                dcc.Checklist(options=[' Set range max to current upper bound'],
                                                        value=[], id="custom-slider-max",
                                labelStyle={"margin-left": "5px", "float": "right", "justify-content": "right"},
                                               style={"width": "100%", "float": "right", "margin-left": "10px",
                                                      "margin-right": "5px", "accent-color": DEFAULT_WIDGET_COLOUR})],
                                style={"display": "flex", "margin": "20px"}),
                                 # html.Div([html.H6("Set range maximum", style={'width': '75%', 'margin-left': '20px'}),
                                 #           dcc.Input(id="custom-slider-max", type="number", value=None,
                                 #                     style={"width": "30%", "margin-left": "20px"})],
                                 #          style={"display": "block"}),
                                 html.Div([dcc.Checklist(options=[' Apply/refresh filter'], value=[],
                                    id="bool-apply-filter", style={"width": "85%", "accent-color": DEFAULT_WIDGET_COLOUR}),
                                 dcc.Dropdown(['median', 'gaussian'], 'median', id='filter-type',
                                              style={"width": "85%", "display": "inline-block"}),
                                 dcc.Input(id="kernel-val-filter", type="number", value=3, style={"width": "50%"},
                                           min=0, max=9, step=1, debounce=True),
                                 dcc.Input(id="sigma-val-filter", type="number", value=1, style={"width": "50%"},
                                           disabled=True, min=0, max=9, step=0.1, debounce=True)],
                                style={"display": "inline-block", "margin": "20px"}),
                                 html.Br(),
                                 dbc.Button(
                                     children=html.Span([html.I(className="fa-solid fa-gears",
                                                                style={"display": "inline-block",
                                                                       "margin-right": "3px"}),
                                                         html.Div("Advanced canvas options"),
                                                         ]),
                                     id="blend-offcanvas-button", className="mx-auto",
                                     color=None, n_clicks=0, style={"display": "flex", "width": "auto",
                                                                    "align-items": "center",
                                                   "float": "center", "justify-content": "center"}),
                                 html.Br(),
                                 dbc.Offcanvas(id="blend-config-offcanvas", title="Advanced settings: canvas & region",
                                               placement="end", style={"width": "32%"}, backdrop=False, scrollable=True,
                                               is_open=False, children=[
                                dbc.Tabs(id='config-tabs',
                                children=[dbc.Tab(label="Configuration", tab_id='blend-config-tab',
                                        label_style={"color": DEFAULT_WIDGET_COLOUR},
                                children=[
                                # need more space for multi options
                                dbc.Tabs(id='config-subtabs', children=[
                                    dbc.Tab(label='Canvas', label_style={"color": DEFAULT_WIDGET_COLOUR},
                                    children=[
                                        html.Br(),
                                        html.Div([daq.ToggleSwitch(label='Toggle legend', id='toggle-canvas-legend',
                                                                   labelPosition='bottom', value=True,
                                                                   color=DEFAULT_WIDGET_COLOUR, style={"width": "75%",
                                                                                                       "margin-left": "-15px"},
                                                                   persistence=config['persistence'],
                                                                   persistence_type='local'),
                                                  daq.ToggleSwitch(label='Toggle scalebar', id='toggle-canvas-scalebar',
                                                                   labelPosition='bottom', value=True,
                                                                   color=DEFAULT_WIDGET_COLOUR,
                                                                   style={"width": "75%", "margin-left": "-15px"},
                                                                   persistence=config['persistence'],
                                                                   persistence_type='local'),
                                                  html.Div(
                                                      [html.H6("Scalebar length (unzoomed)", style={'width': '150%'}),
                                                       dcc.Input(id="custom-scale-val", type="number", value=None,
                                                                 style={"width": "60%", "margin-left": "30px"},
                                                                 debounce=True)],
                                                      style={"display": "block"}),
                                                  html.Div([html.H6("Scale ratio\n(μm/pixel)",
                                                                    style={'width': '75%', 'margin-left': '30px'}),
                                                            dcc.Input(id="pixel-size-ratio", type="number", value=1,
                                                                      style={"width": "60%", "margin-left": "30px"},
                                                                      persistence=config['persistence'],
                                                                      persistence_type='local', debounce=True)],
                                                           style={"display": "block"})
                                                  ], style={"display": "flex"}),
                                        html.Br(),
                                        html.Div(
                                            [html.Abbr(dcc.Checklist(options=[' Show channel intensities on hover'],
                                                                     value=[], id="channel-intensity-hover",
                                                                     style={"width": "90%",
                                                                            "accent-color": DEFAULT_WIDGET_COLOUR}),
                                                       title="WARNING: speed is significantly compromised with this feature, "
                                                             "particularly for large images."),
                                             daq.ToggleSwitch(label='Invert annotation placement',
                                                              id='invert-annotations',
                                                              labelPosition='bottom', value=False,
                                                              color=DEFAULT_WIDGET_COLOUR,
                                                              style={"width": "55%", "margin-left": "-15px"},
                                                              persistence=config['persistence'],
                                                              persistence_type='local')], style={"display": "flex"}),
                                        html.Br(),
                                        html.H6("Adjust legend/scale size"),
                                        dcc.Slider(4, 30, 1, value=16,
                                                   id='legend-size-slider',
                                                   marks={4: 'small', 16: 'default', 30: 'large'},
                                                   persistence=config['persistence'], persistence_type='local'),
                                        html.Br(),
                                        html.H6("Apply global filter"),
                                        html.Div([dcc.Checklist(options=[' Apply/refresh filter'], value=[],
                                                                id="bool-apply-global-filter",
                                                                style={"width": "85%",
                                                                       "accent-color": DEFAULT_WIDGET_COLOUR}),
                                                  dcc.Dropdown(['median', 'gaussian'], 'median',
                                                               id='global-filter-type',
                                                               style={"width": "100%", "display": "inline-block"})],
                                                 style={"display": "flex", "margin": "20px"}),
                                        html.Div([dcc.Dropdown([1, 3, 5, 7, 9], 3, id='global-kernel-val-filter',
                                                               style={"width": "75%"}),
                                                  dcc.Input(id="global-sigma-val-filter", type="number", value=1,
                                                            style={"width": "60%"},
                                                            disabled=True, min=0, max=9, step=0.1)],
                                                 style={"display": "flex", "margin": "20px"}),

                                        html.H5("Mask configuration"),
                                        html.Br(),
                                        html.H6("Set mask array and opacity"),
                                        dcc.Loading(dcc.Dropdown(id='mask-options', multi=False,
                                                                 options=[],
                                                                 style={'width': '100%', 'display': 'inline-block',
                                                                        'margin-right': '-50'}), type="default",
                                                    fullscreen=False,
                                                    color=DEFAULT_WIDGET_COLOUR),
                                        dcc.Slider(0, 100, 2.5, value=35,
                                                   id='mask-blending-slider', marks={0: '0%', 25: '25%',
                                                                                     50: '50%', 75: '75%',
                                                                                     100: '100%'}),
                                        html.Div([html.Div([daq.ToggleSwitch(label='Apply mask', id='apply-mask',
                                                                             labelPosition='bottom',
                                                                             color=DEFAULT_WIDGET_COLOUR,
                                                                             style={"margin-left": "60px"}),
                                                            html.Abbr(dcc.Checklist(options=[' add boundary'],
                                                                                    value=[' add boundary'],
                                                                                    id="add-mask-boundary",
                                                                                    style={"margin-left": "35px",
                                                                                           "margin-top": "10px",
                                                                                           "accent-color": DEFAULT_WIDGET_COLOUR}),
                                                                      title="Use this feature only if the cell boundary was not derived on import"),
                                                            dcc.Checklist(options=[' Show mask ID on hover'],
                                                                          value=[], id="add-cell-id-mask-hover",
                                                                          style={"margin-left": "35px",
                                                                                 "margin-top": "10px",
                                                                                 "accent-color": DEFAULT_WIDGET_COLOUR})],
                                                           style={"display": "flex"})])
                                    ]),
                                    dbc.Tab(label='Gating', label_style={"color": DEFAULT_WIDGET_COLOUR},
                                            children=[
                                                html.Br(),
                                                html.H6("Set gating categories (single/multiple)"),
                                                dcc.Dropdown(id='gating-channel-options', multi=True,
                                                options=[], style={'width': '100%', 'display': 'inline-block',
                                                                    'margin-right': '-50'}),
                                                html.Br(),
                                                html.Br(),
                                                html.H6("Modify gating parameters (normalized range)"),
                                                dcc.Dropdown(id='gating-cur-mod', multi=False,
                                                options=[],style={'width': '100%', 'display': 'inline-block',
                                                                    'margin-right': '-50'}),
                                                html.Br(),
                                                html.Br(),
                                                html.Div([
                                                    dcc.RangeSlider(0, 1, 0.01, value=[0, 1],
                                                                    marks=dict(
                                                                        [(i, str(i)) for i in [0, 0.25, 0.5, 0.75, 1]]),
                                                                    id='gating-slider', allowCross=False,
                                                                    tooltip={"placement": "top",
                                                                             "always_visible": False}),
                                                    html.Br(),
                                                html.Div([
                                                dcc.RadioItems(['intersection', 'union'], 'union',
                                                id='gating-blend-type', style={"margin-top": "7.5px",
                                                "margin-left": "15px", "accent-color": DEFAULT_WIDGET_COLOUR,
                                                "width": "35%"}),
                                                daq.ToggleSwitch(label='Apply gating', id='apply-gating',
                                                labelPosition='bottom', value=False,
                                                color=DEFAULT_WIDGET_COLOUR,
                                                style={"width": "40%", "margin-left": "-10px", "margin-top": "2.5px"}),
                                                html.H6(children=[], id="gating-param-display", style={"width": "60%"}),
                                                ], style={"display": "flex", "width": "100%", "justifyContent": "center"}),
                                            html.Br(),
                                            html.H6("Annotate gated cells", style={"width": "75%"}),
                                            html.Div([dcc.Dropdown(id='quant-annotation-col-gating',
                                            multi=False, options=['ccramic_cell_annotation'],
                                            value="ccramic_cell_annotation", style={"width": "80%"}),
                                            dcc.Input(id="gating-annotation-assignment", type="text", value=None,
                                            placeholder="Add gating annotation",
                                            style={"width": "65%", "margin-left": "1px"})],
                                            style={"justifyContent": "center", "display": "flex"}),
                                            dbc.Button(children=html.Span([html.I(className="fa-solid fa-layer-group",
                                            style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                                            html.Div("Create gating annotation")], style={"display": "flex"}),
                                            id="gating-annotation-create", className="mx-auto", color=None, n_clicks=0,
                                            style={"margin-top": "10px"}),
                                            ]),
                                ]),
                                ], style={"margin-top": "10px"}),
                                ]),
                                dbc.Tab(label="Region/presets",
                                label_style={"color": DEFAULT_WIDGET_COLOUR},
                                tab_id='region-config-tab',
                                children=[dbc.Button(children=html.Span([html.I(className="fa-solid fa-chart-area",
                                style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                                html.Div("Show/hide region statistics")], style={"display": "flex"}),
                                id="compute-region-statistics", className="mx-auto", color=None, n_clicks=0,
                                style={"margin-top": "10px"}),
                                html.Br(),
                                html.Div(dbc.Collapse(html.Div([html.H6("Selection information",
                                style={'width': '75%'}),
                                html.Div([dash_table.DataTable(id='selected-area-table',
                                columns=[{'id': p, 'name': p} for p in ['Channel', 'Mean', 'Max', 'Min', 'Total', 'Region']],
                                data=None)], style={"width": "85%"})]),
                                id="area-stats-collapse", is_open=False), style={"margin-bottom": "0px"}),
                                html.Br(),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-layer-group",
                                style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                                html.Div("Add region annotation")], style={"display": "flex"}),
                                    id="region-annotation", className="mx-auto", color=None, n_clicks=0,
                                    disabled=True, style={"margin-top": "10px"}),
                                # TODO: toggle to add annotations to quant sheet or not
                                # dcc.Checklist(options=[' add annotations to quantification results'], value=[
                                #     ' add annotations to quantification results'],
                                #     id="quantification-annotation-import", style={"margin-top": "12px",
                                #     "accent-color": DEFAULT_WIDGET_COLOUR, "margin-left": "11.5px"}),
                                # html.Br(),
                                html.Div([dbc.Button(children=html.Span([html.I(className="fa-solid fa-delete-left",
                                style={"display": "inline-block","margin-right": "7.5px","margin-top": "3px"}),
                                html.Div("Clear annotation shapes")],style={"display": "flex"}),
                                id="clear-region-annotation-shapes", className="mx-auto", color=None, n_clicks=0,
                                disabled=False, style={"margin-top": "10px"}),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-delete-left",
                                style={"display": "inline-block", "margin-right": "7.5px",
                                "margin-top": "3px"}), html.Div("Clear ROI annotations")],
                                style={"display": "flex"}), id="clear-annotation_dict",
                                className="mx-auto", color=None, n_clicks=0, style={"margin-top": "10px", "width": "80%"})],
                                style={"display": "flex", "width": "50%"}),
                                html.Div([dbc.Button(children=html.Span([html.I(className="fa-solid fa-rectangle-list",
                                style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                                html.Div("Show ROI annotations")], style={"display": "flex"}),
                                id="show-annotation-table", className="mx-auto", color=None, n_clicks=0,
                                style={"margin-top": "10px"}),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-delete-left",
                                style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                                html.Div("Undo last annotation")], style={"display": "flex"}),
                                id="undo-latest-annotation", className="mx-auto", color=None, n_clicks=0,
                                style={"margin-top": "10px"})
                                          ], style={"display": "flex", "width": "50%"}),
                                html.Br(),
                                html.Br(),
                                html.Div([daq.ToggleSwitch(label='Click annotation', id='enable_click_annotation',
                                labelPosition='bottom', value=False, color=DEFAULT_WIDGET_COLOUR,
                                                           style={"width": "45%","margin-left": "-20px"}),
                                dcc.Checklist(options=[' Add circle on click'], value=[' add circle on click'],
                                                id="click-annotation-add-circle", style={"margin-top": "12px",
                                                "accent-color": DEFAULT_WIDGET_COLOUR}),
                                dcc.Input(id="click-annotation-assignment", type="text", value=None,
                                          placeholder="Add a cell type for click",
                                    style={"width": "65%", "margin-left": "1px"})],
                                         style={"display": "flex"}),
                                dcc.Checklist(options=[' Overlay grid'], value=[],
                                id="overlay-grid-canvas", style={"margin-top": "12px",
                                                        "accent-color": DEFAULT_WIDGET_COLOUR}),
                                html.Br(),
                                dbc.Alert([], color='success', is_open=False, duration=1200, id='click-annotation-alert'),
                                dbc.Modal(children=dbc.ModalBody(
                                [dash_table.DataTable(id='annotation-table', columns=[], data=None, editable=False,
                                filter_action='native', row_selectable='multi', column_selectable='multi'),
                                html.Br(),
                                dbc.Button("Delete selected annotation(s)", id='delete-annotation-tabular',
                                           style={"background-color": DEFAULT_WIDGET_COLOUR})
                                 ]),
                                    id="annotation-preview", size='xl'),
                                # html.Br(),
                                html.Br(),
                                dbc.Button("Create preset", id="preset-button", className="me-1",
                                           style={"background-color": DEFAULT_WIDGET_COLOUR}),
                                html.Br(),
                                dbc.Popover(dcc.Input(id="set-preset", type="text",
                                    placeholder="Create a preset from the current channel", value=None,
                                    style={"width": "100%"}), target="preset-button", trigger="hover"),
                                html.Br(),
                                dcc.Dropdown(options=[], value=None, id='preset-options'),
                                dbc.Tooltip(children="", target="preset-options",
                                                      id="hover-preset-information", trigger="hover"),
                                html.Br(),
                                html.Div([du.Upload(id='upload-point-annotations', max_file_size=1000, max_files=1,
                                text='Re-import point/ click annotations and add to canvas',
                                filetypes=['csv'], upload_id="upload-point-annotations",
                                default_style={'minHeight': 2, 'lineHeight': 2})], style={"height": "10%"}),
                                html.Br(),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-download",
                                style={"display": "inline-block", "margin-right": "7.5px",
                                "margin-top": "3px"}), html.Div("Download quantification CSV w/ annotations")],
                                style={"display": "flex"}), id="btn-download-annotations", className="mx-auto",
                                color=None, n_clicks=0, style={"margin-top": "10px"}),
                                dcc.Download(id="download-edited-annotations"),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-download",
                                style={"display": "inline-block","margin-right": "7.5px","margin-top": "3px"}),
                                html.Div("Download annotations report (PDF)")], style={"display": "flex"}),
                                id="btn-download-annot-pdf", className="mx-auto", color=None, n_clicks=0,
                                style={"margin-top": "10px"}),
                                dcc.Download(id="download-annotation-pdf"),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-download",
                                style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                                html.Div("Download annotation masks (zip)")], style={"display": "flex"}),
                                id="btn-download-annot-mask", className="mx-auto", color=None,
                                n_clicks=0, style={"margin-top": "10px"}),
                                dcc.Download(id="download-annotation-mask"),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-download",
                                style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                                html.Div("Download point/click annotations (CSV)")], style={"display": "flex"}),
                                id="btn-download-points-csv", className="mx-auto", color=None,
                                n_clicks=0, style={"margin-top": "10px"}),
                                dcc.Download(id="download-point-csv"),
                                dbc.Button(children=html.Span([html.I(className="fa-solid fa-download",
                                style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                                html.Div("Download object annotations (region/gating)")], style={"display": "flex"}),
                                id="btn-download-region-csv", className="mx-auto", color=None, n_clicks=0,
                                           style={"margin-top": "10px"}),
                                dcc.Download(id="download-region-csv"),
                                dbc.Modal(children=dbc.ModalBody(
                                [dbc.Row([dbc.Col([html.H6("Create a region annotation")], width=8),
                                          dbc.Col([html.H6("Annotate with cell type")], width=4)]),
                                 dbc.Row([dbc.Col([html.Div([dcc.Input(id="new-annotation-col", type="text",
                                value="", placeholder="Create annotation column",
                                style={"width": "50%", "margin-right": "10px", "height": "50%"}),
                                dbc.Button("Add new annotation column", id="add-annotation-col",
                                className="me-1", style={"margin-top": "-10px",
                                                         "background-color": DEFAULT_WIDGET_COLOUR})],
                                                            style={"display": "flex"})], width=8),
                                dbc.Col([dcc.Dropdown(id='quant-annotation-col',
                                multi=False, options=['ccramic_cell_annotation'],
                                    value="ccramic_cell_annotation")], width=4)]),
                                html.Br(),
                                dbc.Row([dbc.Col([html.Div([dcc.Input(id="region-annotation-name", type="text",
                                value="", placeholder="Annotation title",
                                style={"width": "65%", "margin-right": "10px", "height": "50%"}),
                                dcc.Input(id="region-annotation-body", type="text",
                                value="", placeholder="Annotation description",
                                          style={"width": "65%", "margin-right": "10px", "height": "50%"})],
                                style={"display": "flex"})], width=8),
                                dbc.Col([
                                # dcc.Dropdown(id='region-annotation-cell-types',
                                # multi=False, options=[], placeholder="Select a cell type")
                                dcc.Input(id="region-annotation-cell-types", type="text",
                                value="", placeholder="New cell type", style={"width": "65%", "margin-right": "10px",
                                    "height": "100%"})
                                ], width=4)]),
                                dbc.Row(dbc.Col(html.Div([], style={"display": "flex"}))),
                                dbc.Button("Create annotation", id="create-annotation",
                                className="me-1", style={"margin-top": "10px",
                                "background-color": DEFAULT_WIDGET_COLOUR})]),
                                id="region-annotation-modal", size='xl', style={"margin-left": "10px",
                                "margin-top": "15px"}),
                                html.Br(),
                                ], style={"padding": "5px"}),
                                dbc.Tab(label="Measure/cluster", label_style={"color": DEFAULT_WIDGET_COLOUR},
                                    children=[
                                html.Br(),
                                dbc.Button("Quantify current ROI", id="quantify-cur-roi-button",
                                           style={"background-color": DEFAULT_WIDGET_COLOUR}),
                                html.Br(),
                                html.Br(),
                                html.Div([
                                du.Upload(id='upload-cluster-annotations', max_file_size=10000,
                                text='Import cluster annotations in CSV format',
                                chunk_size=100, max_total_size=10000, max_files=1, filetypes=['csv'],
                                default_style={"height": "0.1%"})], style={"height": "auto"}),
                                html.Div([daq.ToggleSwitch(label='Apply clustering',
                                id='toggle-cluster-annotations', labelPosition='bottom', color=DEFAULT_WIDGET_COLOUR,
                                style={"margin-right": "15px", "margin-top": "10px", 'justifyContent': 'center'}),
                                dcc.RadioItems(['mask', 'circles'], 'mask', id='cluster-annotation-type',
                                style={"margin-top": "7.5px", "margin-left": "15px", "accent-color": DEFAULT_WIDGET_COLOUR}),
                                daq.ToggleSwitch(label='Clustering in legend',
                                    id='cluster-annotations-legend', labelPosition='bottom',
                                    color=DEFAULT_WIDGET_COLOUR, style={"margin-left": "15px", "margin-right": "15px", "margin-top": "10px"})],
                                style={"display": 'flex', 'margin-left': '10px', 'margin-top': '7.5px'}),
                                html.Br(),
                                html.Div([dcc.Dropdown(id='cluster-label-list', multi=False, options=[],
                                style={'width': '60%',
                                'margin-right': '-30', 'margin-left': '15px', 'margin-top': '10px'}),
                                daq.ColorPicker(id="cluster-color-picker", label="Current channel color",
                                                          value=dict(hex="#00ABFC", rgb=None), size=150)],
                                        style={"display": "flex"}),
                                html.H6(children=[], id="cluster-assignments"),
                                dbc.Modal(id="quantification-roi-modal", children=dbc.ModalBody([
                                dbc.Button("Quantify current ROI", id="quantify-cur-roi-execute",
                                           style={"background-color": DEFAULT_WIDGET_COLOUR}),
                                html.Br(),
                                dcc.Checklist(id="quant-toggle-list", value=[' select/deselect all'],
                                options=[' select/deselect all'], style={"accent-color": DEFAULT_WIDGET_COLOUR}),
                                html.Br(),
                                html.H6("Select channels to quantify"),
                                dcc.Checklist(id="channel-quantification-list", value=[], options=[],
                                              style={"accent-color": DEFAULT_WIDGET_COLOUR}),
                                ])),
                                ])], style={"margin-top": "-15px"}),
                                     ]),
                                 html.Div([dbc.Button(
                                     children=html.Span([html.I(className="fa-solid fa-list-check",
                                                                style={"display": "inline-block",
                                                                       "margin-right": "3px"}),
                                                         html.Div("Set blend order"),
                                                         ]),
                                     id="set-sort",
                                     color=None, n_clicks=0, className="mx-auto",
                                     style={"display": "flex", "width": "auto", "align-items": "center",
                                                   "float": "center", "justify-content": "center"}),
                                     dag.AgGrid(
                                     id='blend-options-ag-grid',
                                     rowData=[],
                                     columnDefs=[{'field': 'Channel', 'rowDrag': True}],
                                     defaultColDef={"sortable": False, "filter": False},
                                     columnSize="sizeToFit", style={"height": None},
                                     dashGridOptions={
                                         "rowDragManaged": True,
                                         "animateRows": True,
                                         # "rowDragMultiRow": True,
                                         # "rowSelection": "multiple",
                                         # "rowDragEntireRow": True,
                                         "pagination": False,
                                         "domLayout": "autoHeight",
                                         # "getRowId": False
                                     })], style={"width": "90%", "margin-left": "12.5px", "height": "auto"}),
                                 html.Br(),
                                 html.Br()
                                 ],
                                style={"background-color": "#f8f9fa", "padding": "10px", "display": "inline-block",
                                       "float": "right", "width": "100%"},

                            ),

                        ],width=3),

                    ])])]),

            dbc.Tab(label="Channel gallery", tab_id='gallery-tab', id='gallery-tab',
                    label_style={"color": DEFAULT_WIDGET_COLOUR},
                        children=[
                            html.Br(),
                            html.H6(TabText().channel_tiles),
                            html.Div([daq.ToggleSwitch(label='Change thumbnail on zoom',
                        id='toggle-gallery-zoom', labelPosition='bottom', color=DEFAULT_WIDGET_COLOUR,
                                style={"margin-right": "15px", "margin-top": "10px"}),
                                  daq.ToggleSwitch(label='View gallery by channel',
                                                   id='toggle-gallery-view', labelPosition='bottom',
                                                   color=DEFAULT_WIDGET_COLOUR,
                                                   style={"margin-right": "7px", "margin-top": "10px"}
                                                   ),
                                    daq.ToggleSwitch(label='Use default scaling for preview',
                                                     value=True,
                                                             id='default-scaling-gallery', labelPosition='bottom',
                                                             color=DEFAULT_WIDGET_COLOUR, style={"margin-left": "15px",
                                                                                  "margin-top": "10px"}),
                                            dcc.Dropdown(id='unique-channel-list', multi=False, options=[],
                                                         style={'width': '60%', 'display': 'inline-block',
                                                                'margin-right': '-30', 'margin-left': '15px',
                                                                "margin-top": "10px"})
                                            ],
                                           style={"display": "flex"}),
                        html.Div(id="image-gallery", children=[
                        dbc.Row(id="image-gallery-row")], style={"margin-top": "15px"}),
                                  ]),
            dbc.Tab(label="Panel metadata", tab_id='metadata-tab', label_style={"color": DEFAULT_WIDGET_COLOUR},
                    children=
                        [html.Div([dbc.Row([
                        dbc.Col(html.Div([
                        html.Br(),
                        html.H6(TabText().metadata),
                        html.B("Panel metadata"),
                        html.Br(),
                        dash_table.DataTable(id='imc-metadata-editable', columns=[], data=None,
                                            editable=True)]), width=9),
                        dbc.Col(html.Div([du.Upload(id='upload-metadata', max_file_size=1000, max_files=1,
                                            text='Import panel metadata in CSV format using drag and drop',
                                            filetypes=['csv'], upload_id="upload-image"),
                        html.Br(),
                        html.Button("Download edited metadata", id="btn-download-metadata"),
                        dcc.Download(id="download-edited-table")]),
                            width=3)])])]),
                          dbc.Tab(label="Quantification/clustering", tab_id='quantification-tab',
                                  label_style={"color": DEFAULT_WIDGET_COLOUR},
                                  children=[
                                html.Div([dbc.Row([
                                dbc.Col(html.Div([html.Br(),
                                html.Div([html.B("Cell-level marker expression", style={"margin-bottom": "10px"}),
                                daq.ToggleSwitch(label='Normalize heatmap', id='normalize-heatmap', labelPosition='bottom',
                                    color=DEFAULT_WIDGET_COLOUR, value=True),
                                dcc.Input(type="number", placeholder="Subset heatmap", id="subset-heatmap",
                                          step=1, value=None, debounce=True, style={"width": "20%", "height": "75%",
                                        "margin-left": "50px", "margin-top": "20px"})],
                                style={"display": "flex", "margin-bottom": "-15px"}),
                                    html.Br(),
                                    dcc.Graph(id="quantification-heatmap-full",
                                    figure={'layout': dict(xaxis_showgrid=False, autosize=False,
                                    yaxis_showgrid=False, xaxis=XAxis(showticklabels=False),
                                    yaxis=YAxis(showticklabels=False), margin=dict(l=5, r=5, b=15,
                                    t=20, pad=0))}, responsive=False, config={'displaylogo': False}),
                                    dcc.Checklist(options=[], value=[], id="quant-heatmap-channel-list",
                                    style={"margin-top": "12px", "accent-color": DEFAULT_WIDGET_COLOUR},
                                    inline=True, labelStyle={"margin": "0.12rem"}),
                                    html.Br(),
                                    html.Br()
                                # dbc.Tab(label='Bar plot', id='cell-quant-barplot', tab_id="cell-quant-barplot", children=[
                                #     html.Br(),
                                #     dcc.RadioItems(['max', 'mean', 'min'], 'mean',
                                #                    inline=True, id="quantification-bar-mode"),
                                #     dcc.Graph(id="quantification-bar-full",
                                #               figure={'layout': dict(xaxis_showgrid=False,
                                #                                      yaxis_showgrid=False,
                                #                                      xaxis=XAxis(
                                #                                          showticklabels=False),
                                #                                      yaxis=YAxis(
                                #                                          showticklabels=False),
                                #                                      margin=dict(l=5, r=5, b=15,
                                #                                                  t=20, pad=0)),
                                #                       })
                                # ])
                                ]), width=6),
                                    dbc.Col(html.Div([html.Br(),
                                    html.Div([html.B("Dimension reduction", style={"margin-top": "2.5px"}),
                                    dbc.Button(children=html.Span([html.I(className="fa-regular fa-chart-bar",
                                        style={"display": "inline-block", "margin-right": "7.5px",
                                            "margin-top": "3px"}),
                                    html.Div("UMAP options")], style={"display": "flex",
                                        "margin-top": "-5px","margin-left": "15px"}),
                                        id="umap-config-button", className="mx-auto", color=None, n_clicks=0,
                                        style={"margin-top": "-5px"}),
                                    html.Div([
                                        dbc.Button("Run UMAP", id="execute-umap-button", style={
                                                  "margin-top": "-5px", "margin-right": "30px"},
                                                   color="dark", outline=True),
                                        dbc.Button("Send to query", id="quantification-query-link",
                                                    style={"margin-right": "30px", "margin-bottom": "7px"},
                                                    color="dark", outline=True)
                                              ],
                                             style={"display": "flex", "justifyContent": "right"}),
                                              ], style={"display": "flex"}),
                                        dbc.Modal(children=dbc.ModalBody([html.Div([
                                        du.Upload(id='upload-umap-coordinates', max_file_size=10000,
                                        text='Import UMAP coordinates in CSV format',
                                        chunk_size=100, max_total_size=10000, max_files=1, filetypes=['csv'],
                                        default_style={"height": "0.1%"})],
                                             style={"height": "auto"}),
                                        dcc.Checklist(options=[' Dynamic update on expression barplot'],
                                        value=[' Dynamic update on expression barplot'],
                                        id="dynamic-update-barplot", style={"margin-top": "12px",
                                            "accent-color": DEFAULT_WIDGET_COLOUR}),
                                        html.Br(),
                                        html.H6("Add annotation to cells"),
                                        dcc.Input(id="annotation-col-quantification", type="text",
                                        value="", placeholder="New annotation category",
                                        style={"width": "55%", "margin-right": "10px", "height": "100%",
                                               "margin-top": "5px"}),
                                        dbc.Button("Add new category", id="add-annot-col-quantification",
                                                       className="me-1", style={"margin-top": "10px",
                                        "background-color": DEFAULT_WIDGET_COLOUR}),
                                        dcc.Dropdown(id='quant-annotation-col-in-tab',
                                        multi=False, options=['ccramic_cell_annotation'],
                                            value="ccramic_cell_annotation", style={"width": "75%"}),
                                        dcc.Input(id="annotation-cell-types-quantification", type="text",
                                        value="", placeholder="New cell type",
                                        style={"width": "55%", "margin-right": "10px", "height": "100%",
                                               "margin-top": "5px"}),
                                        dbc.Button("Annotate UMAP", id="create-annotation-umap",
                                            className="me-1", style={"margin-top": "10px",
                                            "background-color": DEFAULT_WIDGET_COLOUR}),
                                        dbc.Button(children=html.Span([html.I(className="fa-solid fa-download",
                                            style={"display": "inline-block", "margin-right": "7.5px",
                                            "margin-top": "3px"}), html.Div("Download UMAP projection")],
                                            style={"display": "flex"}),
                                            id="btn-download-umap-projection", className="mx-auto",
                                            color=None, n_clicks=0, style={"margin-top": "10px"}),
                                            dcc.Download(id="download-umap-projection")
                                        ]),
                                        id="umap-config-modal", size='l'),
                                    html.Div([dcc.Loading(dcc.Dropdown(id='umap-projection-options', multi=False,
                                    options=[], style={"width": "240%"}), type="default", fullscreen=False,
                                            color=DEFAULT_WIDGET_COLOUR),
                                    dbc.Button(children=html.Span([html.I(className="fa-solid fa-table-list",
                                    style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                                    html.Div("Show distribution")], style={"display": "flex", "margin-bottom": "5px",
                                        "margin-left": "15px"}),
                                    id="show-quant-dist", className="mx-auto", color=None, n_clicks=0,
                                    style={"float": "right", "margin-left": "50px", "justifyContent": "right"})
                                              ],
                                    style={"display": "flex", "justifyContent": "right", "float": "center",
                                           "width": "130%", "margin-top": "10px"}),
                                    dbc.Modal(children=dbc.ModalBody([dash_table.DataTable(id='quant-dist-table',
                                    columns=[], data=None, editable=False, filter_action='native')]),
                                    id="show-quant-dist-table", size='l'),
                                    html.Div([dcc.Graph(id="umap-plot", figure={'layout': dict(xaxis_showgrid=False,
                                    yaxis_showgrid=False, xaxis=XAxis(showticklabels=False),
                                    yaxis=YAxis(showticklabels=False), margin=dict(l=5, r=5, b=15,t=20, pad=0),
                                    autosize=False),
                                    }, responsive=False, config={'displaylogo': False}),
                                    html.Br()],
                                    id="umap-div-holder", style={"display": "None"}),
                                    ]), width=6),
                                    html.Br(),
                                    html.Br()
                                      ])]),
                        dbc.Modal(children=dbc.ModalBody([html.H6("Select the cell type annotation column"),
                        dcc.Dropdown(id='cell-type-col-designation',
                            multi=False, options=[], style={'width': '100%'})]),
                        id="quantification-config-modal", size='l', style={"margin-left": "10px",
                            "margin-top": "15px"})],
                                  ),
            dbc.Tab(label="Dataset gallery", tab_id='dataset-query', label_style={"color": DEFAULT_WIDGET_COLOUR},
                    children=[
                html.Br(),
                html.H6(TabText().region_gallery),
                html.H6("Set number of ROIs to return", style={"margin-top": "15px"}),
                html.Div([dcc.Input(id="dataset-query-number", type="number",
                        placeholder="Number of ROIs to return",
                        value=10, style={"height": "25%"}),
                        dbc.Button(children=html.Span([html.I(className="fa-solid fa-bolt",
                        style={"display": "inline-block", "margin-right": "7.5px", "margin-top": "3px"}),
                        html.Div("Execute query")], style={"display": "flex"}), id="execute-dataset-query",
                        className="mb-3", color="primary", n_clicks=0,
                        style={"margin-left": "10px", "margin-top": "-3px", "background-color": DEFAULT_WIDGET_COLOUR}),
                          ],
                         style={"display": "flex", "margin-top": "15px"}),
                html.Div(id="dataset-query-gallery", children=[
                    dbc.Row(id="dataset-query-gallery-row"),
                    html.Br(),
                    dbc.Button("Load more...", id="dataset-query-additional-load", className="d-grid gap-2 col-3 mx-auto",
                               outline=True, color="dark",
                    style={"justifyContent": "center"}),
                    html.Br()], style={"margin-top": "15px", "display": "none"}),
            ])
                ])
                          ])], id='tab-annotation'),
        wrap_child_in_loading(dcc.Store(id="uploaded_dict"), wrap=config['use_loading']),
        # use a blank template for the lazy loading
        wrap_child_in_loading(dcc.Store(id="uploaded_dict_template"), wrap=config['use_loading']),
        dcc.Store(id="session_config"),
        dcc.Store(id="window_config"),
        dcc.Store(id="param_config"),
        dcc.Store(id="session_alert_config"),
        dcc.Store(id="blending_colours"),
        dcc.Store(id="image_presets"),
        dcc.Store(id="metadata_config"),
        dcc.Store(id="param_blend_config"),
        dcc.Store(id="anndata"),
        dcc.Store(id="image-metadata"),
        dcc.Store(id="canvas-layers"),
        dcc.Store(id="alias-dict"),
        dcc.Store(id="static-session-var"),
        dcc.Store(id="session_config_quantification"),
        wrap_child_in_loading(dcc.Store(id="quantification-dict"), wrap=config['use_loading']),
        dcc.Store(id="mask-dict"),
        dcc.Store(id="mask-uploads"),
        dcc.Store(id="figure-cache"),
        dcc.Store(id="uploads"),
        dcc.Store(id="uploads_cluster"),
        dcc.Store(id="current_canvas_image"),
        dcc.Store(id="umap-projection"),
        dcc.Store(id="annotations-dict"),
        dcc.Store(id="channel-order"),
        dcc.Store(id="umap-legend-categories"),
        dcc.Store(id="dataset-query-gallery-list"),
        dcc.Store(id="quantification-query-indices"),
        dcc.Store(id='cur-umap-subset-category-counts'),
        dcc.Store(id='cur_roi_dimensions'),
        dcc.Store(id='imported-annotations-csv'),
        dcc.Store(id='imported-cluster-frame'),
        dcc.Store(id='cluster-colour-assignments-dict'),
        dcc.Store(id="database-connection"),
        dcc.Store(id="db-saved-configs"),
        dcc.Store(id="gating-dict"),
        dcc.Store(id="gating-cell-list"),
        # maintain a list of cell ids for each ROI from the quant query to subset the mask
        dcc.Store(id='query-cell-id-lists'),
        dcc.Loading(dcc.Store(id="roi-query"), type="default", fullscreen=True, color=DEFAULT_WIDGET_COLOUR),
        EventListener(
            # https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event
            events=[{"event": "keydown",
                     "props": ["keyCode", "key"]}],
            logging=True, id="keyboard-listener"
        ),
    ], style={"margin-left": "20px", "margin-right": "25px", "margin-top": "10px"}, className="dash-bootstrap")
