"""
Module for parsing global coordinates for CosMX FOV
"""
from typing import Union
import numpy as np
import anndata as ad
from rakaia.parsers.spatial import is_spatial_dataset

# set the name in the uns slot in the Anndata where the global slide maximums should be found
# NOTE: that this key is custom-generated by example notebooks and needs to be documented for users to implement individually
# it does not come from any standard pipeline
class CosMXUnsIdentifiers:
    uns_key_identifier = "cosmx_global_max"
    global_slide_max_x_key = "x"
    global_slide_max_y_key = "y"

def cosmx_has_global_slide_coords(adata: Union[str, ad.AnnData]):
    """
    Check that the Anndata object has keys in the `.uns` slot associated with storage of the
    global slide maximum coordinates to allow for stitching
    """
    adata = ad.read_h5ad(adata) if not isinstance(adata, ad.AnnData) else adata
    return is_spatial_dataset(adata) and CosMXUnsIdentifiers.uns_key_identifier in adata.uns and \
        CosMXUnsIdentifiers.global_slide_max_x_key in adata.uns[CosMXUnsIdentifiers.uns_key_identifier] and \
        CosMXUnsIdentifiers.global_slide_max_y_key in adata.uns[CosMXUnsIdentifiers.uns_key_identifier]

def cosmx_global_slide_boundaries(adata: Union[str, ad.AnnData]):
    """
    Get the max x and y slide coordinates from the set of CosMx FOVs
    """
    adata = ad.read_h5ad(adata) if not isinstance(adata, ad.AnnData) else adata
    if cosmx_has_global_slide_coords(adata):
        return (int(adata.uns[CosMXUnsIdentifiers.uns_key_identifier][CosMXUnsIdentifiers.global_slide_max_x_key]),
                int(adata.uns[CosMXUnsIdentifiers.uns_key_identifier][CosMXUnsIdentifiers.global_slide_max_y_key]))
    return None, None

def cosmx_local_fov_position(adata: Union[str, ad.AnnData]):
    """
    Get the top-left most stitch position for the current CosMX ROI
    """
    adata = ad.read_h5ad(adata) if not isinstance(adata, ad.AnnData) else adata
    if cosmx_has_global_slide_coords(adata):
        return tuple(np.min(adata.obsm['spatial'], axis=0).astype(int))
    return None, None
